name: Build SmartPlaylist Plugin (No Upload)

on:
  push:
    branches: [ emby4.8-cn ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Clean previous builds
        run: dotnet clean SmartPlaylist/SmartPlaylist.csproj

      - name: Restore dependencies
        run: dotnet restore SmartPlaylist/SmartPlaylist.csproj

      - name: Build
        run: dotnet build SmartPlaylist/SmartPlaylist.csproj --configuration Release

      - name: List output files for debugging
        run: ls -R SmartPlaylist/bin/Release
