name: Build SmartPlaylist Plugin (Emby 4.8 中文版)

on:
  push:
    branches: [ emby4.8-cn ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Clean previous builds
        run: dotnet clean backend/SmartPlaylist/SmartPlaylist.csproj

      - name: Restore dependencies
        run: dotnet restore backend/SmartPlaylist/SmartPlaylist.csproj

      - name: Build
        run: dotnet build backend/SmartPlaylist/SmartPlaylist.csproj --configuration Release

      - name: Upload SmartPlaylist.dll
        uses: actions/upload-artifact@v3
        with:
          name: SmartPlaylist_Emby4.8_CN
          path: backend/SmartPlaylist/bin/Release/net8.0/SmartPlaylist.dll
